export const PERMISSIONS = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  PATIENT_READ: 'PATIENT_READ',
  PATIENT_WRITE: 'PATIENT_WRITE',
  APPOINTMENT_READ: 'APPOINTMENT_READ',
  APPOINTMENT_WRITE: 'APPOINTMENT_WRITE',
  CLINICAL_READ: 'CLINICAL_READ',
  CLINICAL_WRITE: 'CLINICAL_WRITE',
  TRIAGE_READ: 'TRIAGE_READ',
  TRIAGE_WRITE: 'TRIAGE_WRITE',
  HOSPITALIZATION_READ: 'HOSPITALIZATION_READ',
  HOSPITALIZATION_WRITE: 'HOSPITALIZATION_WRITE',
  LAB_READ: 'LAB_READ',
  LAB_WRITE: 'LAB_WRITE',
  PHARMACY_READ: 'PHARMACY_READ',
  PHARMACY_WRITE: 'PHARMACY_WRITE',
  INVENTORY_READ: 'INVENTORY_READ',
  INVENTORY_WRITE: 'INVENTORY_WRITE',
  BILLING_READ: 'BILLING_READ',
  BILLING_WRITE: 'BILLING_WRITE',
  REPORT_READ: 'REPORT_READ',
  REPORT_EXPORT: 'REPORT_EXPORT',
  ADMIN_READ: 'ADMIN_READ',
  ADMIN_WRITE: 'ADMIN_WRITE',
  AUDIT_READ: 'AUDIT_READ',
} as const

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS]

export type UserRole =
  | 'RECEPTION'
  | 'DOCTOR'
  | 'NURSE'
  | 'LAB_TECHNICIAN'
  | 'PHARMACIST'
  | 'CASHIER'
  | 'DIRECTOR'
  | 'SYSTEM_ADMIN'

export type ViewKey =
  | 'inicio'
  | 'pacientes'
  | 'agenda'
  | 'historia'
  | 'triaje'
  | 'hospitalizacion'
  | 'laboratorio'
  | 'farmacia'
  | 'inventario'
  | 'facturacion'
  | 'reportes'
  | 'administracion'

export const roleLabels: Record<UserRole, string> = {
  RECEPTION: 'Admisión y recepción',
  DOCTOR: 'Personal médico',
  NURSE: 'Enfermería',
  LAB_TECHNICIAN: 'Laboratorio clínico',
  PHARMACIST: 'Farmacia',
  CASHIER: 'Caja y facturación',
  DIRECTOR: 'Dirección',
  SYSTEM_ADMIN: 'Administración del sistema',
}

const common = [PERMISSIONS.DASHBOARD_VIEW] satisfies Permission[]

export const rolePermissions: Record<UserRole, Permission[]> = {
  RECEPTION: [
    ...common,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_WRITE,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.CLINICAL_READ,
    PERMISSIONS.TRIAGE_READ,
    PERMISSIONS.REPORT_READ,
  ],
  DOCTOR: [
    ...common,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.CLINICAL_READ,
    PERMISSIONS.CLINICAL_WRITE,
    PERMISSIONS.TRIAGE_READ,
    PERMISSIONS.HOSPITALIZATION_READ,
    PERMISSIONS.HOSPITALIZATION_WRITE,
    PERMISSIONS.LAB_READ,
    PERMISSIONS.LAB_WRITE,
    PERMISSIONS.PHARMACY_READ,
    PERMISSIONS.REPORT_READ,
  ],
  NURSE: [
    ...common,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.CLINICAL_READ,
    PERMISSIONS.TRIAGE_READ,
    PERMISSIONS.TRIAGE_WRITE,
    PERMISSIONS.HOSPITALIZATION_READ,
    PERMISSIONS.HOSPITALIZATION_WRITE,
    PERMISSIONS.REPORT_READ,
  ],
  LAB_TECHNICIAN: [
    ...common,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.CLINICAL_READ,
    PERMISSIONS.LAB_READ,
    PERMISSIONS.LAB_WRITE,
    PERMISSIONS.REPORT_READ,
  ],
  PHARMACIST: [
    ...common,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.CLINICAL_READ,
    PERMISSIONS.PHARMACY_READ,
    PERMISSIONS.PHARMACY_WRITE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.REPORT_READ,
  ],
  CASHIER: [
    ...common,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_WRITE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
  ],
  DIRECTOR: [
    ...common,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.LAB_READ,
    PERMISSIONS.PHARMACY_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_READ,
  ],
  SYSTEM_ADMIN: Object.values(PERMISSIONS),
}

export const viewPermissions: Record<ViewKey, Permission> = {
  inicio: PERMISSIONS.DASHBOARD_VIEW,
  pacientes: PERMISSIONS.PATIENT_READ,
  agenda: PERMISSIONS.APPOINTMENT_READ,
  historia: PERMISSIONS.CLINICAL_READ,
  triaje: PERMISSIONS.TRIAGE_READ,
  hospitalizacion: PERMISSIONS.HOSPITALIZATION_READ,
  laboratorio: PERMISSIONS.LAB_READ,
  farmacia: PERMISSIONS.PHARMACY_READ,
  inventario: PERMISSIONS.INVENTORY_READ,
  facturacion: PERMISSIONS.BILLING_READ,
  reportes: PERMISSIONS.REPORT_READ,
  administracion: PERMISSIONS.ADMIN_READ,
}

export function permissionsForRole(role: UserRole) {
  return rolePermissions[role]
}

export function isViewKey(value: string | undefined): value is ViewKey {
  return Boolean(value && value in viewPermissions)
}
